import type { OrganizationalMember } from '../types';

// Demo data — replace with real names when available.
// These are used only as fallback when Firestore returns no members.

const DEMO_TERM = '2025-2026';
const DEMO_UID = 'demo';

export const DEMO_ORG_MEMBERS: Omit<OrganizationalMember, 'createdAt' | 'updatedAt'>[] = [
  // ── Student Council ─────────────────────────────────────────────────────────
  {
    id: 'demo-1',
    fullNameAr: 'رئيس المجلس الطلابي',
    fullNameEn: 'Student Council President',
    positionAr: 'رئيس المجلس الطلابي',
    positionEn: 'Student Council President',
    bioAr: 'يقود المجلس الطلابي ويمثل صوت الطلاب في الجامعة العربية المفتوحة - فرع جدة.',
    bioEn: 'Leads the Student Council and represents the student voice at Arab Open University – Jeddah Branch.',
    entityType: 'student_council',
    roleCategory: 'council_president',
    displayOrder: 1,
    status: 'active',
    termYear: DEMO_TERM,
    createdByUid: DEMO_UID,
    updatedByUid: DEMO_UID,
  },
  {
    id: 'demo-2',
    fullNameAr: 'نائب رئيس المجلس',
    fullNameEn: 'Vice President',
    positionAr: 'نائب رئيس المجلس الطلابي',
    positionEn: 'Student Council Vice President',
    bioAr: 'يدعم رئيس المجلس في تنفيذ مبادرات المجلس الطلابي.',
    bioEn: 'Supports the President in executing Student Council initiatives.',
    entityType: 'student_council',
    roleCategory: 'council_vice_president',
    displayOrder: 2,
    status: 'active',
    termYear: DEMO_TERM,
    createdByUid: DEMO_UID,
    updatedByUid: DEMO_UID,
  },
  {
    id: 'demo-3',
    fullNameAr: 'أمين المجلس',
    fullNameEn: 'Secretary',
    positionAr: 'أمين المجلس / منسق المجلس',
    positionEn: 'Secretary / Coordinator',
    bioAr: 'ينظم اجتماعات المجلس ويتولى توثيق القرارات والمراسلات.',
    bioEn: 'Organizes council meetings and oversees documentation and correspondence.',
    entityType: 'student_council',
    roleCategory: 'council_secretary',
    displayOrder: 3,
    status: 'active',
    termYear: DEMO_TERM,
    createdByUid: DEMO_UID,
    updatedByUid: DEMO_UID,
  },
  {
    id: 'demo-4',
    fullNameAr: 'مسؤول الإعلام',
    fullNameEn: 'Media Officer',
    positionAr: 'مسؤول الإعلام',
    positionEn: 'Media Officer',
    bioAr: 'يشرف على التغطية الإعلامية لفعاليات المجلس وإدارة حسابات التواصل الاجتماعي.',
    bioEn: 'Oversees media coverage of council events and manages social media accounts.',
    entityType: 'student_council',
    roleCategory: 'council_officer',
    displayOrder: 4,
    status: 'active',
    termYear: DEMO_TERM,
    createdByUid: DEMO_UID,
    updatedByUid: DEMO_UID,
  },
  {
    id: 'demo-5',
    fullNameAr: 'مسؤول الفعاليات',
    fullNameEn: 'Events Officer',
    positionAr: 'مسؤول الفعاليات',
    positionEn: 'Events Officer',
    bioAr: 'يخطط وينسق فعاليات المجلس الطلابي طوال العام الدراسي.',
    bioEn: 'Plans and coordinates Student Council events throughout the academic year.',
    entityType: 'student_council',
    roleCategory: 'council_officer',
    displayOrder: 5,
    status: 'active',
    termYear: DEMO_TERM,
    createdByUid: DEMO_UID,
    updatedByUid: DEMO_UID,
  },
  {
    id: 'demo-6',
    fullNameAr: 'مشرف الأندية',
    fullNameEn: 'Clubs Supervisor',
    positionAr: 'مشرف الأندية',
    positionEn: 'Clubs Supervisor',
    bioAr: 'يشرف على عمل الأندية الطلابية الخمسة ويضمن التنسيق بينها.',
    bioEn: 'Oversees the five student clubs and ensures coordination between them.',
    entityType: 'student_council',
    roleCategory: 'clubs_supervisor',
    displayOrder: 6,
    status: 'active',
    termYear: DEMO_TERM,
    createdByUid: DEMO_UID,
    updatedByUid: DEMO_UID,
  },
  // ── Computer Club ────────────────────────────────────────────────────────────
  {
    id: 'demo-7',
    fullNameAr: 'رئيس نادي الحاسب',
    fullNameEn: 'Computer Club President',
    positionAr: 'رئيس نادي الحاسب الآلي',
    positionEn: 'Computer Club President',
    bioAr: 'يقود نادي الحاسب الآلي ويشرف على الأنشطة التقنية والبرمجية.',
    bioEn: 'Leads the Computer Club and oversees technical and programming activities.',
    entityType: 'club',
    clubId: 'computer',
    roleCategory: 'club_president',
    displayOrder: 10,
    status: 'active',
    termYear: DEMO_TERM,
    createdByUid: DEMO_UID,
    updatedByUid: DEMO_UID,
  },
  {
    id: 'demo-8',
    fullNameAr: 'نائب رئيس نادي الحاسب',
    fullNameEn: 'Computer Club Vice President',
    positionAr: 'نائب رئيس نادي الحاسب الآلي',
    positionEn: 'Computer Club Vice President',
    bioAr: 'يدعم رئيس النادي في إدارة الأنشطة والفعاليات التقنية.',
    bioEn: 'Supports the club president in managing technical activities and events.',
    entityType: 'club',
    clubId: 'computer',
    roleCategory: 'club_vice_president',
    displayOrder: 11,
    status: 'active',
    termYear: DEMO_TERM,
    createdByUid: DEMO_UID,
    updatedByUid: DEMO_UID,
  },
  // ── Business Club ────────────────────────────────────────────────────────────
  {
    id: 'demo-9',
    fullNameAr: 'رئيس نادي الأعمال',
    fullNameEn: 'Business Club President',
    positionAr: 'رئيس نادي الأعمال',
    positionEn: 'Business Club President',
    bioAr: 'يقود نادي الأعمال ويطور مهارات القيادة والريادة لدى الطلاب.',
    bioEn: 'Leads the Business Club and develops leadership and entrepreneurship skills in students.',
    entityType: 'club',
    clubId: 'business',
    roleCategory: 'club_president',
    displayOrder: 20,
    status: 'active',
    termYear: DEMO_TERM,
    createdByUid: DEMO_UID,
    updatedByUid: DEMO_UID,
  },
  {
    id: 'demo-10',
    fullNameAr: 'نائب رئيس نادي الأعمال',
    fullNameEn: 'Business Club Vice President',
    positionAr: 'نائب رئيس نادي الأعمال',
    positionEn: 'Business Club Vice President',
    bioAr: 'يساهم في تنظيم الفعاليات والأنشطة التجارية والريادية.',
    bioEn: 'Contributes to organizing business and entrepreneurial activities.',
    entityType: 'club',
    clubId: 'business',
    roleCategory: 'club_vice_president',
    displayOrder: 21,
    status: 'active',
    termYear: DEMO_TERM,
    createdByUid: DEMO_UID,
    updatedByUid: DEMO_UID,
  },
  // ── Cultural Club ────────────────────────────────────────────────────────────
  {
    id: 'demo-11',
    fullNameAr: 'رئيس النادي الثقافي',
    fullNameEn: 'Cultural Club President',
    positionAr: 'رئيس النادي الثقافي',
    positionEn: 'Cultural Club President',
    bioAr: 'يقود النادي الثقافي ويعزز التنوع والتراث الثقافي في الجامعة.',
    bioEn: 'Leads the Cultural Club and promotes diversity and cultural heritage at the university.',
    entityType: 'club',
    clubId: 'cultural',
    roleCategory: 'club_president',
    displayOrder: 30,
    status: 'active',
    termYear: DEMO_TERM,
    createdByUid: DEMO_UID,
    updatedByUid: DEMO_UID,
  },
  {
    id: 'demo-12',
    fullNameAr: 'نائب رئيس النادي الثقافي',
    fullNameEn: 'Cultural Club Vice President',
    positionAr: 'نائب رئيس النادي الثقافي',
    positionEn: 'Cultural Club Vice President',
    bioAr: 'يدعم الأنشطة الثقافية والفنية في النادي.',
    bioEn: 'Supports cultural and artistic activities within the club.',
    entityType: 'club',
    clubId: 'cultural',
    roleCategory: 'club_vice_president',
    displayOrder: 31,
    status: 'active',
    termYear: DEMO_TERM,
    createdByUid: DEMO_UID,
    updatedByUid: DEMO_UID,
  },
  // ── Sports Club ──────────────────────────────────────────────────────────────
  {
    id: 'demo-13',
    fullNameAr: 'رئيس النادي الرياضي',
    fullNameEn: 'Sports Club President',
    positionAr: 'رئيس النادي الرياضي',
    positionEn: 'Sports Club President',
    bioAr: 'يقود النادي الرياضي ويعزز اللياقة البدنية وروح الفريق.',
    bioEn: 'Leads the Sports Club and promotes physical fitness and team spirit.',
    entityType: 'club',
    clubId: 'sports',
    roleCategory: 'club_president',
    displayOrder: 40,
    status: 'active',
    termYear: DEMO_TERM,
    createdByUid: DEMO_UID,
    updatedByUid: DEMO_UID,
  },
  {
    id: 'demo-14',
    fullNameAr: 'نائب رئيس النادي الرياضي',
    fullNameEn: 'Sports Club Vice President',
    positionAr: 'نائب رئيس النادي الرياضي',
    positionEn: 'Sports Club Vice President',
    bioAr: 'يساهم في تنظيم الفعاليات الرياضية والبطولات الجامعية.',
    bioEn: 'Contributes to organizing sports events and university tournaments.',
    entityType: 'club',
    clubId: 'sports',
    roleCategory: 'club_vice_president',
    displayOrder: 41,
    status: 'active',
    termYear: DEMO_TERM,
    createdByUid: DEMO_UID,
    updatedByUid: DEMO_UID,
  },
  // ── Media Club ───────────────────────────────────────────────────────────────
  {
    id: 'demo-15',
    fullNameAr: 'رئيس النادي الإعلامي',
    fullNameEn: 'Media Club President',
    positionAr: 'رئيس النادي الإعلامي',
    positionEn: 'Media Club President',
    bioAr: 'يقود النادي الإعلامي ويشرف على إنتاج المحتوى الإبداعي.',
    bioEn: 'Leads the Media Club and oversees creative content production.',
    entityType: 'club',
    clubId: 'media',
    roleCategory: 'club_president',
    displayOrder: 50,
    status: 'active',
    termYear: DEMO_TERM,
    createdByUid: DEMO_UID,
    updatedByUid: DEMO_UID,
  },
  {
    id: 'demo-16',
    fullNameAr: 'نائب رئيس النادي الإعلامي',
    fullNameEn: 'Media Club Vice President',
    positionAr: 'نائب رئيس النادي الإعلامي',
    positionEn: 'Media Club Vice President',
    bioAr: 'يدعم إنتاج المحتوى الإعلامي والتصوير والتصميم.',
    bioEn: 'Supports media content production, photography, and design.',
    entityType: 'club',
    clubId: 'media',
    roleCategory: 'club_vice_president',
    displayOrder: 51,
    status: 'active',
    termYear: DEMO_TERM,
    createdByUid: DEMO_UID,
    updatedByUid: DEMO_UID,
  },
];
